### ISSUE TITLE
Issues with IGRIDA

### ISSUE THREAD

**Issue by FAMILIAR-project** [HugoJPMartin/rf-analysis#3]
```
Starting
Train size 98
Fold 0
Traceback (most recent call last):
  File "./index.py", line 30, in <module>
    ml.start()
  File "/app/tux.py", line 134, in start
    results, feature_importance = self._runRF(train_size)
  File "/app/tux.py", line 95, in _runRF
    X_train, X_test, y_train, y_test = train_test_split(self.dataset.drop(columns=self.columns_to_drop), self.dataset[self.perf], train_size=train_size)
  File "/usr/lib/python3.7/site-packages/sklearn/model_selection/_split.py", line 2124, in train_test_split
    safe_indexing(a, test)) for a in arrays))
  File "/usr/lib/python3.7/site-packages/sklearn/model_selection/_split.py", line 2124, in <genexpr>
    safe_indexing(a, test)) for a in arrays))
  File "/usr/lib/python3.7/site-packages/sklearn/utils/__init__.py", line 208, in safe_indexing
    return X.iloc[indices]
  File "/usr/lib/python3.7/site-packages/pandas/core/indexing.py", line 1500, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/usr/lib/python3.7/site-packages/pandas/core/indexing.py", line 2221, in _getitem_axis
    return self._get_list_axis(key, axis=axis)
  File "/usr/lib/python3.7/site-packages/pandas/core/indexing.py", line 2200, in _get_list_axis
    return self.obj._take(key, axis=axis)
  File "/usr/lib/python3.7/site-packages/pandas/core/generic.py", line 3359, in _take
    verify=True)
  File "/usr/lib/python3.7/site-packages/pandas/core/internals/managers.py", line 1350, in take
    axis=axis, allow_dups=True)
  File "/usr/lib/python3.7/site-packages/pandas/core/internals/managers.py", line 1235, in reindex_indexer
    for blk in self.blocks]
  File "/usr/lib/python3.7/site-packages/pandas/core/internals/managers.py", line 1235, in <listcomp>
    for blk in self.blocks]
  File "/usr/lib/python3.7/site-packages/pandas/core/internals/blocks.py", line 1238, in take_nd
    allow_fill=True, fill_value=fill_value)
  File "/usr/lib/python3.7/site-packages/pandas/core/algorithms.py", line 1651, in take_nd
    out = np.empty(out_shape, dtype=dtype)
MemoryError


Fails
End
```

and it seems impossible to set memory 
with `m=30g`
`WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.`

**Comment by FAMILIAR-project** [comment]
something like `oarsub -I -l core=4,walltime=1 -p "virt='YES' and mem_node > 15*1024"` 
works! (we need memory!)
